# Generated by Django 4.2.6 on 2023-10-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_oder_order_date_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
