# Generated by Django 4.2.6 on 2023-10-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_customer_shippingaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='Customer',
        ),
    ]
