# Generated by Django 4.2.6 on 2023-10-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_customer_shippingaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
